title: Bangla Lorem 
email: russelcucse@gmail.com
keywords: Bangla Lorem Text, Bangla Placeholder Text, Bangla Dami Text, Bangla Nomuna Lekha, Lorem Bangla Text, বাংলা লোরেম টেক্সট, বাংলা প্লেসহোল্ডার ডামি টেক্সট, বাংলা ডামি টেক্সট, লোরেম টেক্সট, লোরেম লেখা, প্লেসহোল্ডার বাংলা নমুনা লেখা, লোরেম নমুনা লেখা, বাংলা নমুনা লেখা, নমুনা লেখা 
description: Bangla Placeholder Dummy Text Generator

url: "https://banglalorem.github.io/"
twitter_username: 
github_username: 

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
